### ISSUE TITLE
Problem with Javascript objects with Mongo ObjectId

### ISSUE THREAD

**Issue by yiannistsi** [avrora/key-del#1]
Hi,

I have a JSON object coming from Mongo:
{ "_id" : ObjectId("54a12e61c77c3ae01a84dba5"),
    "user" : "demo",
    "status" : "approved"
}
If I run:
return_obj = deleteKey(obj, fields);
where var fields = ["status"];

I get the following return_obj:
{ "_id": {
    "_bsontype": "ObjectID",
    "id": "U\ ÙÞ^¶©"
    },
"user" : "demo"
}

**Comment by miktam** [comment]
Fixed in #3 

You can modify original object now, in you case: 

```
return_obj = deleteKey(obj, fields, {copy: false});
// should delete the key without messing with ObjectId
```

As alternative (if you dont want to modify original object), you can always do this:

```
return_obj = JSON.parse(JSON.stringify(return_obj))
// it will transform Mongo's ObjectId to _id
```
