### ISSUE TITLE
Delete nested keys by full path

### ISSUE THREAD

**Issue by yiannistsi** [avrora/key-del#2]
It would be nice if we could delete keys from nested objects by their full path (in case the key is named the same in several different nested objects but you only want to delete some of them), i.e.:

var originalObject = {
    one: 1,
    two: 2,
    three: {
      nestedOne: 3,
      nestedTwo: 4
    },
    four: {
      nestedOne: 5,
      nestedTwo: 6
    }
}
var result = deleteKey(originalObject, ['one', 'three.nestedOne']) or like
var result = deleteKey(originalObject, ['one', '[three][nestedOne]')

**Comment by miktam** [comment]
Implemented in 1.2
