### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by yiannistsi** [avrora/key-del#5]
While trying to delete a nested key, I am getting:

c:\node\project\node_modules\key-del\index.js:60
          delete nestedObjectRef[lastAttribute];
                                 ^
TypeError: Cannot convert undefined or null to object
    at c:\node\project\node_modules\key-del\index.js:60:34
    at Array.forEach (native)
    at deleteKeysFromObject (c:\node\project\node_modules\key-del\index.js:43:16)
    at c:\node\project\node_modules\key-del\index.js:64:33
    at Array.forEach (native)
    at deleteKeysFromObject (c:\node\project\node_modules\key-del\index.js:43:16)
    at c:\node\project\routes\v1\profile.js:229:58
    at c:\node\project\node_modules\async\lib\async.js:254:17
    at done (c:\node\project\node_modules\async\lib\async.js:135:19)
    at c:\node\project\node_modules\async\lib\async.js:32:16

**Comment by miktam** [comment]
@yiannistsi, could you provide an example of the object which fails, please?

**Comment by yiannistsi** [comment]
@miktam, here is the object:
{"data":{"_id":"user1","images_folder":"54f084eecdf6a09017ffcd7d","local":true,"settings":{"moto":"Life is beautiful!","description":"Searching for Freedom and peace of mind...","display_name":"user1","official_image_type":"jpg","background_image_style":"cover","profile_searchable":true,"background_image_type":"predefined","background_image":"/backgrounds/bg.png","profile_image_type":"predefined","profile_image":"/avatars/icon.png"},"profile":{"user_id":"user1","name":"User","surname":"1","role":"test"},"relationship":{"is_friend":false,"requested_by":"user2","blocked_by_me":false,"blocked_by_other":false}},"meta":{"code":200}}

I am getting the error either when trying to delete a 2nd level nested key (i.e. data.communities) or a 3rd level one: data.settings.official_image_type

**Comment by miktam** [comment]
@yiannistsi thank you, will fix it today

**Comment by yiannistsi** [comment]
@miktam, just tested it. The deletion of the nested key seems to work. However when I insert in the array of keys to delete both 1st level and 2nd level elements I get the same error. But when I insert 2nd and 3rd level elements it works fine!

**Comment by miktam** [comment]
You are right, will fix it.

**Comment by miktam** [comment]
Fixed

@yiannistsi thank you for helping :)
